lbworkflow/urls.py
from django.urls import path

from .views import flowchart, processinstance
from .views.list import ListWF, MyWF, Todo
from .views.transition import (
    AddAssigneeView,
    BatchExecuteAgreeTransitionView,
    BatchExecuteGiveUpTransitionView,
    BatchExecuteRejectTransitionView,
    ExecuteAgreeTransitionView,
    ExecuteBackToTransitionView,
    ExecuteGiveUpTransitionView,
    ExecuteRejectTransitionView,
    ExecuteTransitionView,
    execute_transitions,
)

urlpatterns = [
    path("t/", ExecuteTransitionView.as_view(), name="wf_execute_transition"),
    path("t/agree/", ExecuteAgreeTransitionView.as_view(), name="wf_agree"),
    path(
        "t/back_to/", ExecuteBackToTransitionView.as_view(), name="wf_back_to"
    ),
    path("t/reject/", ExecuteRejectTransitionView.as_view(), name="wf_reject"),
    path(
        "t/give_up/", ExecuteGiveUpTransitionView.as_view(), name="wf_give_up"
    ),
    path("t/add_assignee/", AddAssigneeView.as_view(), name="wf_add_assignee"),
    path(
        "t/batch/agree/",
        BatchExecuteAgreeTransitionView.as_view(),
        name="wf_batch_agree",
    ),
    path(
        "t/batch/reject/",
        BatchExecuteRejectTransitionView.as_view(),
        name="wf_batch_reject",
    ),
    path(
        "t/batch/give_up/",
        BatchExecuteGiveUpTransitionView.as_view(),
        name="wf_batch_give_up",
    ),
    path(
        "t/e/<str:wf_code>/<str:trans_func>/",
        execute_transitions,
        name="wf_execute_transition",
    ),
    path("start_wf/", processinstance.start_wf, name="wf_start_wf"),
    path("report_list/", processinstance.report_list, name="wf_report_list"),
    path("new/<str:wf_code>/", processinstance.new, name="wf_new"),
    path("delete/", processinstance.delete, name="wf_delete"),
    path("list/<str:wf_code>/", processinstance.show_list, name="wf_list"),
    path("edit/<int:pk>/", processinstance.edit, name="wf_edit"),
    path("<int:pk>/", processinstance.detail, name="wf_detail"),
    path(
        "<int:pk>/print/",
        processinstance.detail,
        {"ext_ctx": {"is_print": True}},
        name="wf_print_detail",
    ),
    path("todo/", Todo.as_view(), name="wf_todo"),
    path("list/", ListWF.as_view(), name="wf_list_wf"),
    path("my/", MyWF.as_view(), name="wf_my_wf"),
    path(
        "flowchart/process/<str:wf_code>/",
        flowchart.process_flowchart,
        name="wf_process_flowchart",
    ),
    path(
        "flowchart/<int:pk>/",
        flowchart.process_instance_flowchart,
        name="wf_process_instance_flowchart",
    ),
]

lbworkflow/forms.py
from django import forms
from django.contrib import messages
from django.contrib.auth import get_user_model
from django_select2.forms import ModelSelect2MultipleWidget
from lbattachment.models import LBAttachment
from lbutils import BootstrapFormHelperMixin, JustSelectedSelectMultiple

from lbworkflow.models import Event, Task

User = get_user_model()

try:
    from crispy_forms.bootstrap import StrictButton
    from crispy_forms.helper import FormHelper
    from crispy_forms.layout import Layout
except ImportError:
    pass


class BSSearchFormMixin(BootstrapFormHelperMixin):
    def layout(self):
        self.helper.layout = Layout(
            "q_quick_search_kw",
            StrictButton(
                "Search", type="submit", css_class="btn-sm btn-default"
            ),
        )

    def init_form_helper(self):
        self.add_class2fields("input-sm")
        self.helper = helper = FormHelper()
        helper.form_class = "form-inline"
        helper.form_method = "get"
        helper.field_template = "bootstrap3/layout/inline_field.html"
        self.layout()


class QuickSearchFormMixin(forms.Form):
    q_quick_search_kw = forms.CharField(label="Key word", required=False)


class BSQuickSearchForm(BSSearchFormMixin, QuickSearchFormMixin, forms.Form):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.init_form_helper()


class BSQuickSearchWithExportForm(BSQuickSearchForm):
    def layout(self):
        self.helper.layout = Layout(
            "q_quick_search_kw",
            StrictButton(
                "Search", type="submit", css_class="btn-sm btn-default"
            ),
            StrictButton(
                "Export",
                type="submit",
                name="export",
                css_class="btn-sm btn-default",
            ),
        )


class WorkflowFormMixin:
    def save_new_process(self, request, wf_code):
        submit = request.POST.get("act_submit")
        act_name = request.POST.get("act_submit") or "Save"
        obj = self.save(commit=False)
        obj.created_by = request.user
        obj.create_pinstance(wf_code, submit)
        self.save_m2m()
        # Other action
        messages.info(
            request,
            "Success %s: %s"
            % (
                act_name,
                obj,
            ),
        )
        return obj

    def update_process(self, request):
        submit = request.POST.get("act_submit")
        act_name = request.POST.get("act_submit") or "Save"
        obj = self.save()
        # add a edit event, change resolution to draft
        instance = obj.pinstance
        if instance.cur_node.status in ["rejected", "draft", "given up"]:
            Task.objects.filter(
                instance=instance, status="in progress"
            ).delete()
            Event.objects.create(
                instance=instance,
                old_node=instance.cur_node,
                new_node=instance.process.get_draft_active(),
                act_type="edit",
                user=request.user,
            )
            instance.cur_node = instance.process.get_draft_active()
            instance.save()
        can_resubmit = instance.cur_node.status in ["draft"]
        # Other action
        if submit and can_resubmit:
            obj.submit_process(request.user)
        messages.info(
            request,
            "Submitted %s: %s"
            % (
                act_name,
                obj,
            ),
        )
        return obj


class WorkFlowForm(forms.Form):
    attachments = forms.ModelMultipleChoiceField(
        label="Attachment",
        queryset=LBAttachment.objects.all(),
        help_text="",
        widget=JustSelectedSelectMultiple(attrs={"class": "nochosen"}),
        required=False,
    )
    comment = forms.CharField(
        label="Comment", required=False, widget=forms.Textarea()
    )

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop("instance", None)
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        return self.instance

    def save_m2m(self, *args, **kwargs):
        return self.instance


class BSWorkFlowForm(BootstrapFormHelperMixin, WorkFlowForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.init_crispy_helper(label_class="col-md-2", field_class="col-md-8")
        self.layout_fields(
            [
                [
                    "attachments",
                ],
                [
                    "comment",
                ],
            ]
        )


class BatchWorkFlowForm(WorkFlowForm):
    pass


class BSBatchWorkFlowForm(BootstrapFormHelperMixin, BatchWorkFlowForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.init_crispy_helper(label_class="col-md-2", field_class="col-md-8")


class BackToNodeForm(WorkFlowForm):
    back_to_node = forms.ChoiceField(label="Back to", required=True)

    def __init__(self, process_instance, *args, **kwargs):
        super().__init__(*args, **kwargs)
        choices = [
            (e.pk, e.name)
            for e in process_instance.get_can_back_to_activities()
        ]
        self.fields["back_to_node"].choices = choices


class BSBackToNodeForm(BootstrapFormHelperMixin, BackToNodeForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.init_crispy_helper(label_class="col-md-2", field_class="col-md-8")
        self.layout_fields(
            [
                [
                    "back_to_node",
                ],
                [
                    "attachments",
                ],
                [
                    "comment",
                ],
            ]
        )


class UserSelect2MultipleWidget(ModelSelect2MultipleWidget):
    search_fields = [
        "username__icontains",
    ]


class AddAssigneeForm(WorkFlowForm):
    assignees = forms.ModelMultipleChoiceField(
        label="Assignees",
        required=True,
        queryset=User.objects,
        widget=UserSelect2MultipleWidget,
    )

    def __init__(self, *args, **kwargs):
        super(AddAssigneeForm, self).__init__(*args, **kwargs)
        self.init_crispy_helper()


class BSAddAssigneeForm(BootstrapFormHelperMixin, AddAssigneeForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.init_crispy_helper(label_class="col-md-2", field_class="col-md-8")
        self.layout_fields(
            [
                [
                    "assignees",
                ],
                [
                    "attachments",
                ],
                [
                    "comment",
                ],
            ]
        )

lbworkflow/views/flowchart.py
from django.template import Context, Template

from lbworkflow.models import Process, ProcessInstance


def get_event_transitions(process_instance):
    from lbworkflow.models import Event

    events = Event.objects.filter(instance=process_instance).order_by(
        "-created_on", "-id"
    )
    transitions = []
    for event in events:
        transition = (event.old_node, event.new_node)
        if event.new_node.status in ["rejected", "given up"]:
            break
        if transition not in transitions:
            transitions.append(transition)
    return transitions


def generate_mermaid_src(process_instance):
    file_template = """
    {% load lbworkflow_tags %}
    graph TD
    {% for node in nodes %}
    {% if node.node_type == 'router' %}
    {{node.pk}}{ {{node.name}} }
    {% else %}
    {{node.pk}}( {{node.name}} )
    {% endif %}
    {% endfor %}
    {% for transition in transitions %}
    {{ transition.input_node.pk }} {{ transition|mermaid_transition_line:event_transitions|safe }}{% if transition.get_condition_descn %}|{{transition.get_condition_descn}}|{% endif %} {{ transition.output_node.pk }}
    {% endfor %}
    """  # NOQA
    if isinstance(process_instance, Process):
        process = process_instance
        process_instance = None
    else:
        process = process_instance.process

    transitions = process.transition_set.all()
    event_transitions = []
    if process_instance:
        event_transitions = get_event_transitions(process_instance)

    nodes = process.node_set.all()
    ctx = Context(
        {
            "name": process.name,
            "nodes": nodes,
            "transitions": transitions,
            "event_transitions": event_transitions,
        }
    )
    t = Template(file_template)
    return t.render(ctx)


def process_flowchart(request, wf_code):
    from django.shortcuts import render

    template_name = "lbworkflow/flowchart.html"
    process = Process.objects.get(code=wf_code)
    graph_src = generate_mermaid_src(process)
    ctx = {"process": process, "graph_src": graph_src}
    return render(request, template_name, ctx)


def process_instance_flowchart(request, pk):
    from django.shortcuts import render

    template_name = "lbworkflow/flowchart.html"
    process_instance = ProcessInstance.objects.get(pk=pk)
    graph_src = generate_mermaid_src(process_instance)
    ctx = {"process": process_instance.process, "graph_src": graph_src}
    return render(request, template_name, ctx)

lbworkflow/templates/lbworkflow/base_ext.html
{% extends "lbadminlte/base_ext.html" %}

{% block left_side %}
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li id="id-nav-todo">
        <a href="{% url 'wf_todo' %}">
          <i class="fa fa-th"></i> Todo
          <small class="badge pull-right bg-red todo-count hide"></small>
        </a>
      </li>
      <li id="id-nav-mywf">
        <a href="{% url 'wf_my_wf' %}">
          <i class="fa fa-th"></i> My
        </a>
      </li>
      <li id="id-nav-start-wf">
        <a href="{% url 'wf_start_wf' %}">
          <i class="fa fa-th"></i> Submit
        </a>
      </li>
      <li id="id-nav-list-wf">
        <a href="{% url 'wf_list_wf' %}">
          <i class="fa fa-th"></i> All
        </a>
      </li>
      <li id="id-nav-report-list">
        <a href="{% url 'wf_report_list' %}">
          <i class="fa fa-th"></i> Report list
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

lbworkflow/templates/lbworkflow/base_formset.html
{% extends "base_formset.html" %}

{% load static %}

{% block nav_sel_node %}id-nav-mywf{% endblock %}

{% block right_side_content_top %}
  {% if object %}
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" role="tablist" id="id-m-nav-tabs">
        <li class="active">
          <a href="##id-tb-base" role="tab" data-toggle="tab">Base Information</a>
        </li>
        {% block right_side_tab_nav_ext %}
        {% endblock %}
        <li>
          <a href="#id-tb-wf-log" role="tab" data-toggle="tab">Operate history</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="id-tb-base">
          {% block right_side_tab_base_ctx %}
          {% include "lbworkflow/inc_wf_status.html" %}
          {% endblock %}
        </div>
        {% block right_side_tab_ctx_ext %}
        {% endblock %}
        <div class="tab-pane" id="id-tb-wf-log">
          <a href="{% url 'wf_process_flowchart' process.code %}" target="_blank">Flow Chart</a>
          {% include "lbworkflow/inc_wf_history.html" %}
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block right_side_header %}
  <div class="right-btns">
    {% if wf_code %}
      <a target="_black" href="{% url 'wf_process_flowchart' wf_code %}">Flowchart</a>
    {% endif %}
  </div>
  <h1>
    <a href="{% url 'wf_my_wf' %}">My workflow</a>
    &gt;
    {% if object %}
      {{ object }}
    {% else %}
      {{ process.name }}
    {% endif %}
  </h1>
{% endblock %}


{% block form_act_btns %}
  {% if not process_instance.cur_node.is_submitted %}
    <input type="submit" class="btn btn-primary" name="act_submit" value="Submit"/>
  {% endif %}
  <button type="submit" class="btn btn-default" name="act_save">Save</button>
  <button type="button" class="btn btn-default goback" name="act_cancel">Cancel</button>
{% endblock %}

{% block footer_ext %}
  <link href="{% static 'flatpickr/dist/flatpickr.min.css' %}" rel="stylesheet" type="text/css" />
  {{ block.super }}
  <script src="{% static 'blueimp-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.fileupload.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'flatpickr/dist/flatpickr.min.js' %}"></script>
{% endblock %}

lbworkflow/templates/lbworkflow/batch_transition_form.html
{% extends "base_ext.html" %}

{% load lbworkflow_tags %}
{% load crispy_forms_tags %}
{% load static %}

{% block content_nav_l %}
    {{ transition.name }}
{% endblock %}

{% block head_ext %}
  <style>
    #id_comment {
      height: 80px;
    }
  </style>
{% endblock %}

{% block right_side %}
  <section class="content-header">
    {% include "incs/messages.html" %}
    <div class="right-btns">
    </div>
    <h1>
      Batch
      -
      {{ transition_name }}
    </h1>
  </section>
  <section class="content">
    <form action="" method="post" id="id-wf-form" role="form">
      <input type="hidden" name="do_submit" value="submit it">
      <div class="box form-horizontal {% block form_class %}{% endblock %}">
        <div class="box-header">
        </div>
        <div class="box-body">
          <div class="form-group">
            <label class="control-label col-md-2">
              Process
            </label>
            <div class="controls col-md-4" style="padding-top:7px">
              {% for o in task_list%}
                <input type="hidden" name="wi" value="{{ o.pk }}">
                <input type="hidden" name="pi" value="{{ o.instance.pk }}">
                {{ o.instance.no }} : {{ o.instance.summary }} <br>
              {% endfor %}
            </div>
          </div>
          {% crispy form %}
          {% block submit_btns %}
            <div class="form-group">
              <div class="col-xs-offset-2 col-xs-6">
                <button type="submit" class="btn btn-primary">
                  {{ transition_name }}
                </button>
                <button type="button" class="btn btn-default goback">Cancel</button>
              </div>
            </div>
          {% endblock %}
        </div>
      </div>
      {% block other_forms %}
      {% endblock %}
    </form>
  </section>
{% endblock %}

{% block footer_ext %}
  {{ block.super }}
  <script src="{% static 'blueimp-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.fileupload.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.iframe-transport.js' %}"></script>
  <script type="text/javascript">
    $(function(){
      initUploader($('#id_attachments'));
    });
  </script>
{% endblock %}

lbworkflow/templates/lbworkflow/do_transition_form.html
{% extends "base_ext.html" %}

{% load lbworkflow_tags %}
{% load crispy_forms_tags %}
{% load static %}

{% block content_nav_l %}
    {{ transition.name }}
{% endblock %}

{% block head_ext %}
  {{ form.media.js }}
  <style>
    #id_comment {
      height: 80px;
    }
  </style>
{% endblock %}

{% block right_side %}
  <section class="content-header">
    {% include "incs/messages.html" %}
    <div class="right-btns">
    </div>
    <h1>
      {{ process.name }}
      -
      {{ object }}
      -
      {{ transition.name }}
    </h1>
  </section>
  <section class="content">
    <form action="" method="post" id="id-wf-form" role="form">
      <div class="box form-horizontal {% block form_class %}{% endblock %}">
        <div class="box-header">
        </div>
        <div class="box-body">
          <div class="form-group">
            <label class="control-label col-xs-2">Current node</label>
            <div class="controls col-xs-6">
              <span class="text-block">
                {{ transition.input_node.name }}
              </span>
            </div>
          </div>
          {% if backto_node_form %}
            <div class="form-group">
              <label class="control-label col-xs-2">Next node</label>
              <div class="controls col-xs-6">
                {{ backto_node_form.backto_node }}
              </div>
            </div>
          {% endif %}
          {% crispy form %}
          {% block submit_btns %}
            <div class="form-group">
              <div class="col-xs-offset-2 col-xs-6">
                <button type="submit" class="btn btn-primary">
                  {{ transition.name }}
                </button>
                <button type="button" class="btn btn-default goback">Cancel</button>
              </div>
            </div>
          {% endblock %}
        </div>
      </div>
      {% block other_forms %}
      {% endblock %}
    </form>
  </section>
{% endblock %}

{% block footer_ext %}
  {{ block.super }}
  <link href="{% static 'flatpickr/dist/flatpickr.min.css' %}" rel="stylesheet" type="text/css" />
  <script src="{% static 'flatpickr/dist/flatpickr.min.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.fileupload.js' %}"></script>
  <script src="{% static 'blueimp-file-upload/js/jquery.iframe-transport.js' %}"></script>
  {{ form.media.js }}
  <script type="text/javascript">
    $(function(){
      initUploader($('#id_attachments'));
    });
  </script>
{% endblock %}

lbworkflow/templates/lbworkflow/flowchart.html
{% extends "base.html" %}

{% load static %}

{% block body %}
<div style="margin: 10px;">
  <h1>{{ process.name }}</h1>
  <div class="mermaid">
    {{ graph_src }}
  </div>
</div>
{% endblock %}

{% block footer_ext %}
<script src="{% static 'mermaid/dist/mermaid.min.js' %}" type="text/javascript"></script>
<script>
  mermaid.initialize({startOnLoad:true});
</script>
{% endblock %}

lbworkflow/templates/lbworkflow/inc_wf_btns.html
{% load lbworkflow_tags %}

{% for t in agree_transitions  %}
  <a class="{% if is_btn %}btn btn-primary{% endif %}" href="{{ t|app_url:task }}">{{ t.name }}</a>
  <span>|</span>
{% endfor %}
{% for t in other_transitions  %}
  <a class="{% if is_btn %}btn btn-primary{% endif %}" href="{{ t|app_url:task }}">{{ t.name }}</a>
  <span>|</span>
{% endfor %}
{% if task  %}
<a class="{% if is_btn %}btn btn-primary{% endif %}" href="{% url 'wf_add_assignee' %}?wi_id={{ task.pk }}">Add assignee</a>
<span>|</span>
{% endif %}
{% if can_reject  %}
  <a class="{% if is_btn %}btn btn-danger{% endif %}" href="{% url 'wf_reject' %}?wi_id={{ task.pk }}">Reject</a>
  <span>|</span>
{% endif %}
{% if can_back_to %}
  <a class="{% if is_btn %}btn btn-danger{% endif %}" href="{% url 'wf_back_to' %}?wi_id={{ task.pk }}">Back to</a>
  <span>|</span>
{% endif %}
{# TODO hold and add joint #}
{% comment %}
  {% if can_rollback %}
    <a class="{% if is_btn %}btn btn-default{% endif %}"
       href="{% url 'wf_rollback' %}?pk={{ process_instance.pk }}">
      Rollback
    </a>
    <span>|</span>
  {% endif %}
{% endcomment %}
{% if can_give_up %}
  <a class="{% if is_btn %}btn btn-default{% endif %}"
     href="{% url 'wf_give_up' %}?pk={{ process_instance.pk }}">Give up</a>
  <span>|</span>
{% endif %}

{% if not is_btn %}
  {% if can_edit %}
    <a class="{% if is_btn %}btn btn-default{% endif %}" class="with-next" href="{% url 'wf_edit' process_instance.pk %}">Edit</a>
    <span>|</span>
  {% endif %}
  {% if is_wf_admin %}
    <a class="{% if is_btn %}btn btn-danger{% endif %} btn-del" href="{% url 'wf_delete' %}?pk={{ process_instance.pk }}">Delete</a>
    <span>|</span>
  {% endif %}
{% endif %}

lbworkflow/templates/lbworkflow/inc_wf_history.html
<table class="table table-bordered gray-th wf-act-history">
  <tbody>
    <tr>
      <th>On</th>
      <th>User</th>
      <th>Action</th>
      <th>Old node</th>
      <th>New node</th>
      <th>Note</th>
      <th>Notice users</th>
    </tr>
    {% for e in wf_history %}
      <tr>
        <td>{{ e.created_on|date:"Y-m-d H:i" }}</td>
        <td>{{ e.user }}</td>
        <td>{{ e.get_act_name }}</td>
        <td>{{ e.old_node.name }}</td>
        <td>{{ e.new_node.name }}</td>
        <td>
          {% if e.comment %}
            {{ e.comment|linebreaksbr }}
          {% endif %}
          {% for a in e.attachments.all %}
            <a href="{% url 'lbattachment_download' %}?pk={{ a.pk }}">{{ a.filename }}</a>
            <br>
          {% endfor %}
        </td>
        <td>
          {{ e.get_next_notice_users_display }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

lbworkflow/templates/lbworkflow/inc_wf_status.html
<table class="table table-bordered tb-detail wf-act-history">
  <tr>
    <th class="w-mid">NO.</th>
    <td class="process-no">
      {{ process_instance.no }}
    </td>
    <th class="w-mid">Created by</th>
    <td>{{ process_instance.created_by }}</td>
  </tr>
  <tr>
    <th>Created on</th>
    <td>{{ process_instance.created_on|date:"Y-m-d H:i" }}</td>
    <th>Current node</th>
    <td>
      {{ process_instance.cur_node.name }}
      {% if task.is_hold %}
        (hold)
      {% endif %}
    </td>
  </tr>
  <tr>
    <th>Process name</th>
    <td>{{ process.name }}</td>
    <th>Current operator</th>
    <td>
      {{ operators_display }}
      {% if not process_instance.has_received %}
          [unreceived]
      {% endif %}
    </td>
  </tr>
</table>

lbworkflow/templates/lbworkflow/list_wf.html
{% extends "base_ext.html" %}

{% load crispy_forms_tags %}
{% load bootstrap_pagination %}
{% load lbworkflow_tags %}

{% block nav_sel_node %}id-nav-list-wf{% endblock %}

{% block right_side %}
  <section class="content-header">
    {% include "incs/messages.html" %}
    <div class="right-btns">
        <a href="{% url 'wf_start_wf' %}">
          Submit a new workflow
        </a>
    </div>
    <h1>
      All flow
    </h1>
  </section>
  <section class="content">
    <div class="box">
      {% if search_form %}
      <div class="box-header">
        <div class="input-group show-label-form">
          {% crispy search_form %}
        </div>
      </div>
      {% endif %}
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>NO.</th>
              <th>Process name</th>
              <th>Summary</th>
              <th>Created on</th>
              <th>Created by</th>
              <th>Current operator</th>
              <th>Node</th>
            </tr>
            {% for pi in object_list %}
              <tr>
                <td><a href="{% url 'wf_detail' pi.pk %}">{{ pi.no }}</a></td>
                <td>{{ pi.process.name }}</td>
                <td>{{ pi.summary }}</td>
                <td>{{ pi.created_on|date:"Y-m-d H:i" }}</td>
                <td>{{ pi.created_by }}</td>
                <td>{{ pi.get_operators_display }}</td>
                <td>
                  <span class="label label-{{ pi|flow_status_css_class }}">
                    {{ pi.cur_node.name }}
                  </span>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="box-footer clearfix">
        {% bootstrap_paginate page_obj %}
      </div>
    </div>
  </section>
{% endblock %}

lbworkflow/templates/lbworkflow/my_wf.html
{% extends "base_ext.html" %}

{% load crispy_forms_tags %}
{% load bootstrap_pagination %}
{% load lbworkflow_tags %}

{% block nav_sel_node %}id-nav-mywf{% endblock %}

{% block right_side %}
  <section class="content-header">
    {% include "incs/messages.html" %}
    <div class="right-btns">
        <a href="{% url 'wf_start_wf' %}">Submit a new workflow</a>
    </div>
    <h1>
        I submitted
    </h1>
  </section>
  <section class="content">
    <div class="box">
      {% if search_form %}
        <div class="box-header">
          <div class="input-group">
            {% crispy search_form %}
          </div>
        </div>
      {% endif %}
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>NO.</th>
              <th>Process name</th>
              <th>Summary</th>
              <th>Created on</th>
              <th>Current operator</th>
              <th>Node</th>
            </tr>
            {% for pi in object_list %}
              <tr>
                <td><a href="{% url 'wf_detail' pi.pk %}">{{ pi.no }}</a></td>
                <td>{{ pi.process.name }}</td>
                <td>{{ pi.summary }}</td>
                <td>{{ pi.created_on|date:"Y-m-d H:i" }}</td>
                <td>{{ pi.get_operators_display }}</td>
                <td>
                  <span class="label label-{{ pi|flow_status_css_class }}">
                    {{ pi.cur_node.name }}
                  </span>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="box-footer clearfix">
        {% bootstrap_paginate page_obj %}
      </div>
    </div>
  </section>
{% endblock %}